spring:
 cloud:
    gateway:
      routes:
      - id: restaurantservice
        uri: lb://BRINKERLIST
        predicates:
          - Path=/restaurant/**
      - id: foodservice
        uri: lb://BRINKERINCFOODCATALOUGE
        predicates:
          - Path=/foodcatalouge/**
      - id: userservice
        uri: lb://BRINKERUSER
        predicates:
          - Path=/user/**
      - id: orderservice
        uri: lb://ORDERSERVICE
        predicates:
          - Path=/order/**
 application:
    name: APIGATEWAY

 
server:
  port: 3333




